// <auto-generated />
using System;
using ContractClaimMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractClaimMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251121140918_FreshStart")]
    partial class FreshStart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ContractClaimMvc.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<int>("LecturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedByName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            HourlyRate = 250m,
                            HoursWorked = 40m,
                            LecturerId = 2,
                            LecturerName = "Dr. John Smith",
                            Notes = "Monthly teaching hours for August",
                            Status = "Pending",
                            SubmittedDate = new DateTime(2025, 11, 19, 16, 9, 17, 334, DateTimeKind.Local).AddTicks(308)
                        },
                        new
                        {
                            ClaimId = 2,
                            HourlyRate = 250m,
                            HoursWorked = 35m,
                            LecturerId = 2,
                            LecturerName = "Dr. John Smith",
                            Notes = "Research supervision hours",
                            ProcessedById = 3,
                            ProcessedByName = "Prof. Sarah Wilson",
                            ProcessedDate = new DateTime(2025, 11, 20, 16, 9, 17, 334, DateTimeKind.Local).AddTicks(1658),
                            Status = "Approved",
                            SubmittedDate = new DateTime(2025, 11, 16, 16, 9, 17, 334, DateTimeKind.Local).AddTicks(1648)
                        });
                });

            modelBuilder.Entity("ContractClaimMvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 11, 21, 16, 9, 17, 329, DateTimeKind.Local).AddTicks(2288),
                            Department = "Administration",
                            Email = "hr@abc.com",
                            EmployeeId = "HR001",
                            FullName = "HR Administrator",
                            HourlyRate = 0m,
                            IsActive = true,
                            Password = "123456",
                            Role = "HR"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 11, 21, 16, 9, 17, 332, DateTimeKind.Local).AddTicks(2790),
                            Department = "Computer Science",
                            Email = "lecturer@abc.com",
                            EmployeeId = "LEC001",
                            FullName = "Dr. John Smith",
                            HourlyRate = 250m,
                            IsActive = true,
                            Password = "123456",
                            Role = "Lecturer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 11, 21, 16, 9, 17, 332, DateTimeKind.Local).AddTicks(2859),
                            Department = "Academic Affairs",
                            Email = "coordinator@abc.com",
                            EmployeeId = "CO001",
                            FullName = "Prof. Sarah Wilson",
                            HourlyRate = 0m,
                            IsActive = true,
                            Password = "123456",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 11, 21, 16, 9, 17, 332, DateTimeKind.Local).AddTicks(2864),
                            Department = "Management",
                            Email = "manager@abc.com",
                            EmployeeId = "MGR001",
                            FullName = "Dr. Michael Brown",
                            HourlyRate = 0m,
                            IsActive = true,
                            Password = "123456",
                            Role = "Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
