// <auto-generated />
using System;
using ContractClaimMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContractClaimMvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("ContractClaimMvc.Models.Claim", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("TEXT");

                    b.Property<int>("LecturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LecturerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProcessedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProcessedByName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ClaimId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = 1,
                            HourlyRate = 250m,
                            HoursWorked = 40m,
                            LecturerId = 2,
                            LecturerName = "John Lecturer",
                            Notes = "Monthly teaching hours",
                            Status = "Pending",
                            SubmittedDate = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ClaimId = 2,
                            HourlyRate = 250m,
                            HoursWorked = 35m,
                            LecturerId = 2,
                            LecturerName = "John Lecturer",
                            Notes = "Research supervision",
                            ProcessedById = 3,
                            ProcessedByName = "Sarah Coordinator",
                            ProcessedDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Approved",
                            SubmittedDate = new DateTime(2024, 12, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ContractClaimMvc.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Administration",
                            Email = "hr@abc.com",
                            EmployeeId = "HR001",
                            FullName = "HR Admin",
                            HourlyRate = 0m,
                            IsActive = true,
                            Password = "123456",
                            Role = "HR"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Computer Science",
                            Email = "lecturer@abc.com",
                            EmployeeId = "LEC001",
                            FullName = "John Lecturer",
                            HourlyRate = 250m,
                            IsActive = true,
                            Password = "123456",
                            Role = "Lecturer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Academic Affairs",
                            Email = "coordinator@abc.com",
                            EmployeeId = "CO001",
                            FullName = "Sarah Coordinator",
                            HourlyRate = 0m,
                            IsActive = true,
                            Password = "123456",
                            Role = "Coordinator"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Management",
                            Email = "manager@abc.com",
                            EmployeeId = "MGR001",
                            FullName = "Mike Manager",
                            HourlyRate = 0m,
                            IsActive = true,
                            Password = "123456",
                            Role = "Manager"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
